### ISSUE TITLE
Additional properties for Student objects

### ISSUE THREAD

**Issue by dondi** [dondi/headmaster#1]
Some properties to add/modify:
- Boolean active, indicating if a student is no longer in a program, without having to delete the student record
- Multiple email addresses (and other contacts?)

**Comment by rowedonalde** [comment]
Right on.

(I'm still alive. Just slothal.)

**Comment by dondi** [comment]
Better slothal than unemployed, right?  :)  Headmaster has seen some big progress lately—take a look when you can.

BTW have not forgotten about your dining philosophers.  Took a quick look at it already actually, weeks ago, but didn’t manage to go more in-depth.  That’s still on my to-do list, hasn’t been forgotten.

**Comment by dondi** [comment]
OK, this is done, both on the service side and now on the client side.
